# Generated by Django 6.0.6 on 2026-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('weekly', 'Weekly Celebration'), ('midweek', 'Mid-Week Prayer'), ('special', 'Special Conference')], default='weekly', max_length=20)),
                ('description', models.TextField()),
                ('date_time_info', models.CharField(help_text='e.g., Sundays at 09:00 AM', max_length=100)),
                ('location_info', models.CharField(help_text='e.g., Main Sanctuary & Online', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sermon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('series', models.CharField(default='Standalone Activation', max_length=255)),
                ('description', models.TextField()),
                ('video_url', models.URLField(help_text='Link to YouTube or video stream')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
