# Generated by Django 6.0.6 on 2026-06-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Church Event', 'verbose_name_plural': 'Church Events'},
        ),
        migrations.AlterModelOptions(
            name='sermon',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Sermon', 'verbose_name_plural': 'Sermons'},
        ),
        migrations.AddField(
            model_name='sermon',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='Original YouTube publish date', null=True),
        ),
        migrations.AddField(
            model_name='sermon',
            name='slug',
            field=models.SlugField(blank=True, help_text='Auto-generated from title', unique=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sermon',
            name='video_url',
            field=models.URLField(help_text='Link to YouTube or video stream', unique=True),
        ),
    ]
